<?xml version="1.0"?>
<robot name="axis" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="axis" params="prefix parent size *origin">
        <!-- AXIS Details -->
        <xacro:property name="axis_width" value="0.186"/>
        <xacro:property name="axis_height" value="0.3748"/>
        <xacro:property name="axis_long_length" value="2.299"/>
        <xacro:property name="axis_short_length" value="2.299"/>

        <xacro:property name="axis_table_length" value="0.28013"/>
        <xacro:property name="axis_bearing_length" value="0.039"/>
        <xacro:property name="axis_gearbox_length" value="0.082"/>

        <xacro:if value="${size == 'short'}">
            <xacro:property name="axis_length" value="${axis_short_length}"/>
        </xacro:if>
        <xacro:unless value="${size == 'short'}">
            <xacro:property name="axis_length" value="${axis_long_length}"/>
        </xacro:unless>
        <!-- AXIS -->
        <link name="${prefix}axis">
            <visual>
                <geometry>
                    <mesh filename="package://linearaxis_description/meshes/axis-${size}.stl"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="${axis_length/2.} ${-axis_width/2.} ${-axis_height/2.}" rpy="0 0 0"/>
                <geometry>
                    <box size="${axis_length} ${axis_width} ${axis_height}"/>
                </geometry>
            </collision>
        </link>
        <!-- Reference -->
        <link name="${prefix}reference">
        <visual>
                <geometry>
                    <mesh filename="package://linearaxis_description/meshes/axis-table.stl"/>
                </geometry>
        </visual>
        </link>
        <!-- Parent to Axis -->
        <joint name="${parent}to_axis" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${prefix}axis"/>
            <xacro:insert_block name="origin"/>
        </joint>
        <!-- Axis to Reference -->
        <joint name="${prefix}axis_to_reference" type="prismatic">
            <parent link="${prefix}axis"/>
            <child link="${prefix}reference"/>
            <limit effort="1000" velocity="1.0" lower="${axis_bearing_length + axis_table_length/2.}" upper="${axis_length - axis_bearing_length - axis_table_length/2. - axis_gearbox_length}"/>
            <origin rpy ="0 0 0" xyz="0 ${-axis_width/2.} ${axis_height/2.}"/>
        </joint>
    </xacro:macro>
</robot>